apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replicas:
  - name: octo-server
    count: 2
  - name: octo-web
    count: 2
  - name: octo-admin
    count: 2
  - name: octo-smart-summary-api
    count: 2
