apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: mininglamposs/octo-server
    newTag: dev
  - name: mininglamposs/octo-web
    newTag: dev
  - name: mininglamposs/octo-admin
    newTag: dev
  - name: mininglamposs/octo-matter
    newTag: dev
  - name: mininglamposs/octo-smart-summary-api
    newTag: dev
  - name: mininglamposs/octo-smart-summary-worker
    newTag: dev
