-- +migrate Up

ALTER TABLE `space` MODIFY COLUMN `updated_at` timeStamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `space_member` MODIFY COLUMN `updated_at` timeStamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `space_invitation` MODIFY COLUMN `updated_at` timeStamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
