import { ChannelTypeGroup, ChannelTypePerson } from "wukongimjssdk";
import type { DocumentState } from "./types";

export const initialDocumentState: DocumentState = {
  spaces: [
    {
      id: "space-east-delivery",
      name: "华东交付部空间",
      owner: "刘青",
      fileCount: 128,
      memberCount: 42,
      members: ["刘青", "张沐", "陈一", "王珂"],
      boundConversations: ["华东项目交付群"],
      pinnedFileIds: ["DOC-240617-001"],
      description: "沉淀客户交付材料、项目计划和现场实施记录",
    },
    {
      id: "space-product",
      name: "产品部公共空间",
      owner: "陈一",
      fileCount: 94,
      memberCount: 18,
      members: ["陈一", "王珂", "李维", "韩霄"],
      boundConversations: ["产品方案讨论群"],
      pinnedFileIds: ["DOC-240617-002"],
      description: "管理需求清单、竞品资料和评审结论",
    },
    {
      id: "space-hr",
      name: "人力公共空间",
      owner: "赵宁",
      fileCount: 36,
      memberCount: 11,
      members: ["赵宁", "张沐", "周岚"],
      boundConversations: ["人力运营群"],
      pinnedFileIds: [],
      description: "沉淀制度、入离职资料和共享说明",
    },
    {
      id: "space-policy",
      name: "公司制度空间",
      owner: "周岚",
      fileCount: 57,
      memberCount: 326,
      members: ["周岚", "赵宁", "王珂"],
      boundConversations: ["行政制度发布群"],
      pinnedFileIds: [],
      description: "公司级正式制度、公告和版本记录",
    },
  ],
  files: [
    {
      id: "DOC-240617-001",
      name: "Q3 客户现场实施计划.pdf",
      kind: "pdf",
      extension: "pdf",
      size: 18_400_000,
      owner: "张沐",
      uploader: "张沐",
      sourceName: "华东项目交付群",
      sourceChannelId: "group-east-delivery",
      sourceChannelType: ChannelTypeGroup,
      sourceType: "群聊",
      spaceName: "华东交付部空间",
      visibility: "space",
      status: "archived",
      createdAt: "2026-06-12 09:42",
      lastAccessAt: "2026-06-17 09:18",
      downloads: 42,
      previewable: true,
      flow: ["上传到华东项目交付群", "归档到华东交付部空间", "空间权限已复核"],
    },
    {
      id: "DOC-240617-002",
      name: "Octo 文件空间需求清单.xlsx",
      kind: "sheet",
      extension: "xlsx",
      size: 2_100_000,
      owner: "陈一",
      uploader: "陈一",
      sourceName: "产品方案讨论群",
      sourceChannelId: "group-product-plan",
      sourceChannelType: ChannelTypeGroup,
      sourceType: "群聊",
      spaceName: "产品部公共空间",
      visibility: "space",
      status: "archived",
      createdAt: "2026-06-15 15:26",
      lastAccessAt: "2026-06-17 10:02",
      downloads: 18,
      previewable: true,
      flow: ["上传到产品方案讨论群", "标记为需求文档", "归档到产品部公共空间"],
    },
    {
      id: "DOC-240617-003",
      name: "客户账号权限确认截图.png",
      kind: "image",
      extension: "png",
      size: 820_000,
      owner: "李维",
      uploader: "李维",
      sourceName: "李维 / 韩霄 单聊",
      sourceChannelId: "u-liwei",
      sourceChannelType: ChannelTypePerson,
      sourceType: "单聊",
      spaceName: "会话文件",
      visibility: "conversation",
      status: "conversation",
      createdAt: "2026-06-16 11:03",
      lastAccessAt: "2026-06-16 11:10",
      downloads: 3,
      previewable: true,
      flow: ["单聊上传", "双方可见", "尚未归档"],
    },
    {
      id: "DOC-240617-004",
      name: "离职交接资料包.zip",
      kind: "zip",
      extension: "zip",
      size: 76_900_000,
      owner: "张沐",
      uploader: "张沐",
      sourceName: "人力运营群",
      sourceChannelId: "group-hr-ops",
      sourceChannelType: ChannelTypeGroup,
      sourceType: "群聊",
      spaceName: "会话文件",
      visibility: "conversation",
      status: "conversation",
      createdAt: "2026-06-10 18:21",
      lastAccessAt: "2026-06-14 08:34",
      downloads: 7,
      previewable: false,
      flow: ["上传到人力运营群", "进入会话文件", "等待离职交接"],
    },
    {
      id: "DOC-240617-005",
      name: "制度更新说明.docx",
      kind: "doc",
      extension: "docx",
      size: 1_600_000,
      owner: "周岚",
      uploader: "周岚",
      sourceName: "行政制度发布群",
      sourceChannelId: "group-policy",
      sourceChannelType: ChannelTypeGroup,
      sourceType: "群聊",
      spaceName: "公司制度空间",
      visibility: "space",
      status: "deleted",
      createdAt: "2026-06-01 10:05",
      lastAccessAt: "2026-06-05 16:32",
      downloads: 25,
      previewable: true,
      flow: ["上传到行政制度发布群", "归档到公司制度空间", "管理员删除，保留在回收站"],
    },
  ],
  audits: [
    {
      id: "AUD-001",
      time: "2026-06-17 10:12",
      actor: "系统",
      action: "权限校验",
      target: "Octo 文件空间需求清单.xlsx",
      detail: "空间成员访问，允许预览",
    },
    {
      id: "AUD-002",
      time: "2026-06-17 09:51",
      actor: "管理员 王珂",
      action: "归档",
      target: "Q3 客户现场实施计划.pdf",
      detail: "从华东项目交付群归档到华东交付部空间",
    },
    {
      id: "AUD-003",
      time: "2026-06-16 18:06",
      actor: "管理员 王珂",
      action: "删除",
      target: "制度更新说明.docx",
      detail: "移动到回收站，保留期 30 天",
    },
  ],
};
