package main

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// Prefix-to-group routing (D18). err.shared.* lives in the SDK and follows
// pkg/i18n/locales/; everything else (err.server.* and the reserved msg.*
// namespace) is server-private and ships under the repo-root locales/.
//
// The mapping is closed: unknown prefixes are a hard error. That guarantees
// that introducing a third namespace forces an explicit routing decision
// (and a Code.ID regex update in pkg/i18n/codes/registry.go).
//
// NOTE: `msg.` is a Phase 2 placeholder. pkg/i18n/codes/registry.go's
// idPattern currently restricts IDs to `err.(shared|server).*`, so any
// attempt to Register a `msg.*` Code panics at startup and never reaches
// extraction. The routing entry is intentionally pre-wired so that when
// Phase 2 widens the registry regex, this table doesn't need a parallel
// edit. Any future maintainer touching one side must update both.
var prefixGroup = map[string]string{
	"err.shared.": "shared",
	"err.server.": "server",
	"msg.":        "server",
}

// GroupByPrefix routes markers into their target group ("shared" or "server").
// Returns an error if any marker's ID does not match a known prefix.
func GroupByPrefix(ms []Marker) (map[string][]Marker, error) {
	out := make(map[string][]Marker)
	for _, m := range ms {
		group, ok := groupFor(m.ID)
		if !ok {
			return nil, fmt.Errorf("marker %q: unrecognized ID prefix (expected one of err.shared./err.server./msg.)", m.ID)
		}
		out[group] = append(out[group], m)
	}
	for g := range out {
		ms := out[g]
		sort.SliceStable(ms, func(i, j int) bool { return ms[i].ID < ms[j].ID })
		out[g] = ms
	}
	return out, nil
}

func groupFor(id string) (string, bool) {
	for prefix, g := range prefixGroup {
		if strings.HasPrefix(id, prefix) {
			return g, true
		}
	}
	return "", false
}

// RenderTOML produces a deterministic go-i18n marker file. Format matches
// what `goi18n merge` expects as a source: one `["id"]` table per Code with
// a single `other = "..."` key, alphabetized by ID, LF line endings, trailing
// newline. Stable output is a precondition for the CI extract-diff check.
func RenderTOML(ms []Marker) string {
	sorted := append([]Marker(nil), ms...)
	sort.SliceStable(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })

	var buf bytes.Buffer
	buf.WriteString(markerHeader)
	for i, m := range sorted {
		if i > 0 {
			buf.WriteByte('\n')
		}
		// strconv.Quote handles \n, \t, embedded quotes and unicode safely;
		// go-i18n's TOML parser accepts standard basic strings.
		fmt.Fprintf(&buf, "[%s]\nother = %s\n", strconv.Quote(m.ID), strconv.Quote(m.DefaultMessage))
	}
	return buf.String()
}

const markerHeader = `# AUTO-GENERATED by pkg/i18n/cmd/octo-i18n-extract. DO NOT EDIT.
#
# Source-of-truth marker file: one entry per codes.Register / errcode.register
# call in the repo. Regenerate with ` + "`make i18n-extract`" + `; the merge into
# active.<lang>.toml is performed by goi18n merge (see Makefile).
#
# CI rejects PRs that change codes.Register input without re-running extract.

`

// WriteMarkerFile writes content (RenderTOML output) to path, creating the
// parent directory if needed. Returns changed=true only when on-disk bytes
// differ from the new payload, enabling cheap idempotency checks in CI.
func WriteMarkerFile(path string, ms []Marker) (changed bool, err error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, fmt.Errorf("mkdir %s: %w", filepath.Dir(path), err)
	}
	want := []byte(RenderTOML(ms))
	got, err := os.ReadFile(path)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return false, fmt.Errorf("read %s: %w", path, err)
	}
	if bytes.Equal(got, want) {
		return false, nil
	}
	if err := os.WriteFile(path, want, 0o644); err != nil {
		return false, fmt.Errorf("write %s: %w", path, err)
	}
	return true, nil
}
