import type { BusinessCardPayload } from "@octo/base/src/Messages/BusinessCard/BusinessCardContent";

const matterStateFixtures = [
  {
    id: "matter-card-backlog",
    status: "backlog",
    label: "暂存",
    title: "客户合同风险条款待排期",
    body: "销售已把客户合同 v3 放入 Matter，等待 PM 排期后推进法务评审。",
    owner: "PM 排期",
    progress: "0 / 4",
    statusText: "已暂存，等待排期",
  },
  {
    id: "matter-card-open",
    status: "open",
    label: "待处理",
    title: "客户合同风险条款待处理",
    body: "Matter 已创建，当前需要法务先确认付款节点和违约责任。",
    owner: "法务同学",
    progress: "1 / 4",
    statusText: "已交给法务同学",
  },
  {
    id: "matter-card-in-progress",
    status: "in_progress",
    label: "进行中",
    title: "客户合同风险条款处理中",
    body: "法务正在补充红线条款说明，销售同步客户侧承诺口径。",
    owner: "法务同学",
    progress: "2 / 4",
    statusText: "法务同学正在处理",
  },
  {
    id: "matter-card-review",
    status: "review",
    label: "等你看",
    title: "风险说明已回传，等待 PM 确认",
    body: "法务已给出红线条款说明，销售补充了客户侧承诺口径。",
    owner: "赵倩笑 PM",
    progress: "3 / 4",
    statusText: "东西回来了，等你确认",
  },
  {
    id: "matter-card-blocked",
    status: "blocked",
    label: "受阻",
    title: "客户合同评审受阻",
    body: "客户侧尚未确认上线前交付范围，法务暂时无法给出最终结论。",
    owner: "销售负责人",
    progress: "2 / 4",
    statusText: "卡住了：客户待补充书面确认",
  },
  {
    id: "matter-card-done",
    status: "done",
    label: "已完成",
    title: "完成客户合同 v3 评审",
    body: "事项已完成，合同评审结论已同步到群聊，相关附件可在 Matter 详情中查看。",
    owner: "已完成",
    progress: "4 / 4",
    statusText: "已验收完成，结果可回看",
  },
  {
    id: "matter-card-cancelled",
    status: "cancelled",
    label: "已取消",
    title: "客户合同评审已取消",
    body: "客户本轮合同版本不再推进，Matter 保留过程记录供后续追溯。",
    owner: "无需处理",
    progress: "1 / 4",
    statusText: "已取消，原因可回看",
  },
  {
    id: "matter-card-archived",
    status: "archived",
    label: "已归档",
    title: "客户合同评审已归档",
    body: "合同评审 Matter 已归档，关键结论和历史状态仍可回看。",
    owner: "已归档",
    progress: "4 / 4",
    statusText: "已归档，记录可回看",
  },
];

const makeMatterCard = (
  fixture: (typeof matterStateFixtures)[number]
): BusinessCardPayload => ({
  id: fixture.id,
  cardType: "matter_status",
  title: fixture.title,
  subtitle: "销售一群 · Matter 状态返回",
  body: fixture.body,
  status: fixture.status,
  priority:
    fixture.status === "blocked" || fixture.status === "review" ? "P0" : "P1",
  source: "Matter",
  actor: "赵倩笑 PM",
  time: "今天 10:24",
  entityId: fixture.id,
  entityType: "matter",
  sourceChannelId: "sales-group-1",
  sourceChannelType: 2,
  metrics: [
    { label: "现在该谁处理", value: fixture.owner },
    { label: "截止", value: "2026/06/25 12:26" },
    { label: "进度", value: fixture.progress },
  ],
  actions: [
    { label: "进入 Matter", type: "open_matter_workspace", kind: "primary" },
    { label: "预览", type: "open_matter", kind: "ghost" },
  ],
  extra: {
    matterNo: "M-1001",
    statusText: fixture.statusText,
    sourceName: "Richcard 验收群",
    agentName: "Brooks",
    agentRole: "带队",
    participantText: "3 个参与者",
    participantRoles: ["法务", "销售"],
    progress: fixture.progress,
    updateCount: 4,
    statusHistory: [
      {
        id: `${fixture.id}-1`,
        statusText: "从群消息创建 Matter",
        title: "客户合同审批进入法务复核",
        actor: "赵倩笑 PM",
        time: "10:12",
      },
      {
        id: `${fixture.id}-2`,
        statusText: "分派参与者",
        title: "销售、法务和 PM 已进入协同",
        actor: "Brooks",
        time: "10:18",
      },
      {
        id: `${fixture.id}-3`,
        statusText: "补充上下文",
        title: "合并付款节点、违约责任和上线范围信息",
        actor: "Brooks",
        time: "10:24",
      },
      {
        id: `${fixture.id}-4`,
        statusText: fixture.label,
        title: fixture.statusText,
        actor: "Brooks",
        time: "10:31",
      },
    ],
  },
});

export const mockRichCardPayloads: BusinessCardPayload[] = [
  ...matterStateFixtures.map(makeMatterCard),
  {
    id: "summary-feedback-card",
    cardType: "summary_feedback",
    title: "客户项目周会总结",
    subtitle: "群总结反馈",
    body: "本周重点集中在交付排期、合同评审和数据权限确认。风险项是客户侧验收环境仍未完全开放，需要项目负责人继续推进。",
    status: "done",
    source: "智能总结",
    actor: "Octo AI",
    time: "今天 11:30",
    entityId: "summary-20260618",
    entityType: "summary",
    sourceChannelId: "sales-group-1",
    sourceChannelType: 2,
    metrics: [
      { label: "消息数", value: "128" },
      { label: "来源", value: "1 个群" },
      { label: "参与人", value: "8 人" },
    ],
    actions: [
      { label: "查看总结", type: "open_summary", kind: "primary" },
      { label: "认可", type: "summary_accept", kind: "secondary" },
      { label: "需要调整", type: "summary_reject", kind: "secondary" },
    ],
  },
  {
    id: "external-link-card",
    cardType: "external_link",
    title: "飞书开放平台：消息卡片设计规范",
    subtitle: "外部链接卡片 · 后续扩展场景",
    body: "外部分享链接可自动解析标题、摘要、来源和操作按钮，作为富格式卡片能力的自然扩展。",
    source: "外部链接",
    time: "今天 12:02",
    entityId: "https://open.feishu.cn",
    entityType: "url",
    metrics: [{ label: "来源", value: "open.feishu.cn" }],
    actions: [
      {
        label: "打开链接",
        type: "open_url",
        kind: "primary",
        url: "https://open.feishu.cn",
      },
    ],
  },
];
