import type { BusinessCardPayload } from "@octo/base/src/Messages/BusinessCard/BusinessCardContent";

export const mockRichCardPayloads: BusinessCardPayload[] = [
  {
    id: "matter-card-open",
    cardType: "matter_status",
    title: "完成「客户合同评审」事项",
    subtitle: "销售一群 · Matter 状态返回",
    body: "法务已补充关键风险点，等待销售负责人确认最终版本。",
    status: "open",
    priority: "P0",
    source: "Matter",
    actor: "张倩潇",
    time: "今天 10:24",
    entityId: "matter-10086",
    entityType: "matter",
    sourceChannelId: "sales-group-1",
    sourceChannelType: 2,
    metrics: [
      { label: "现在该谁处理", value: "法务同学" },
      { label: "截止", value: "今天 18:00" },
      { label: "进度", value: "2 / 4" },
    ],
    actions: [
      { label: "进入 Matter", type: "open_matter_workspace", kind: "primary" },
      { label: "预览", type: "open_matter", kind: "ghost" },
      { label: "标记完成", type: "complete_matter", kind: "secondary" },
    ],
    extra: {
      matterNo: "M-1001",
      statusText: "法务同学正在处理",
      sourceName: "Richcard 验收群",
      agentName: "Brooks",
      agentRole: "带队",
      participantText: "3 个参与者",
      participantRoles: ["法务", "销售"],
      progress: "2 / 4",
      updateCount: 4,
      statusHistory: [
        { id: "m-1001-1", statusText: "从群消息创建事项", title: "客户合同审批进入法务复核", actor: "赵倩笑 PM", time: "10:12" },
        { id: "m-1001-2", statusText: "法务同学正在处理", title: "客户合同审批进入法务复核", actor: "Brooks", time: "10:18" },
        { id: "m-1001-3", statusText: "销售同学补充客户口径", title: "补充付款和违约条款背景", actor: "Brooks", time: "10:24" },
        { id: "m-1001-4", statusText: "法务同学正在处理", title: "等待风险说明回传", actor: "Brooks", time: "10:31" },
      ],
    },
  },
  {
    id: "matter-card-done",
    cardType: "matter_status",
    title: "完成「客户合同评审」事项",
    subtitle: "销售一群 · Matter 状态返回",
    body: "事项已完成，合同评审结论已同步到群聊，相关附件可在事项详情中查看。",
    status: "done",
    source: "Matter",
    actor: "李雷",
    time: "今天 11:08",
    entityId: "matter-10086",
    entityType: "matter",
    sourceChannelId: "sales-group-1",
    sourceChannelType: 2,
    metrics: [
      { label: "负责人", value: "2 人" },
      { label: "耗时", value: "44 分钟" },
      { label: "状态", value: "已完成" },
    ],
    actions: [
      { label: "查看事项", type: "open_matter", kind: "primary" },
    ],
  },
  {
    id: "summary-feedback-card",
    cardType: "summary_feedback",
    title: "客户项目周会总结",
    subtitle: "群总结反馈",
    body: "本周重点集中在交付排期、合同评审和数据权限确认。风险项是客户侧验收环境仍未完全开放，需要项目负责人继续推进。",
    status: "done",
    source: "智能总结",
    actor: "Octo AI",
    time: "今天 11:30",
    entityId: "summary-20260618",
    entityType: "summary",
    sourceChannelId: "sales-group-1",
    sourceChannelType: 2,
    metrics: [
      { label: "消息数", value: "128" },
      { label: "来源", value: "1 个群" },
      { label: "参与人", value: "8 人" },
    ],
    actions: [
      { label: "查看总结", type: "open_summary", kind: "primary" },
      { label: "认可", type: "summary_accept", kind: "secondary" },
      { label: "需要调整", type: "summary_reject", kind: "secondary" },
    ],
  },
  {
    id: "external-link-card",
    cardType: "external_link",
    title: "飞书开放平台：消息卡片设计规范",
    subtitle: "外部链接卡片 · 后续扩展场景",
    body: "外部分享链接可自动解析标题、摘要、来源和操作按钮，作为富格式卡片能力的自然扩展。",
    source: "外部链接",
    time: "今天 12:02",
    entityId: "https://open.feishu.cn",
    entityType: "url",
    metrics: [
      { label: "来源", value: "open.feishu.cn" },
    ],
    actions: [
      { label: "打开链接", type: "open_url", kind: "primary", url: "https://open.feishu.cn" },
    ],
  },
];
